language: generic
sudo: required
services:
        - docker

before_install:
        - docker build -t rcollier1972/docker-react -f Dockerfile.dev .
script:
        - docker run -e CI=true rcollier1972/docker-react npm run test

deploy:
        provider: elasticbeanstalk
        region: "us-east-2"
#DockerReact-env.eba-9nppd8tc.us-east-2.elasticbeanstalk.com
        app: "docker-react"
        env: "DockerReact-env"
        bucket_name: "elasticbeanstalk-us-east-2-725421609531"
        bucket_path: "docker-react"
        on:
                branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY

